; ---------------------------------------------------------------
;  ใบงานที่ 5 : PIR Motion -> Relay + LED  (จำลองด้วย Wokwi)
;  คณะเทคโนโลยีสารสนเทศ มหาวิทยาลัยราชภัฏร้อยเอ็ด
; ---------------------------------------------------------------
[env:esp32doit-devkit-v1]
platform      = espressif32
board         = esp32doit-devkit-v1
framework     = arduino
monitor_speed = 115200
